services:
  api:
    build: .
    container_name: api
    ports:
      - 8080:8080
    environment:
      JOURNEY_DATABASE_NAME: ${JOURNEY_DATABASE_NAME}
      JOURNEY_DATABASE_USER: ${JOURNEY_DATABASE_USER}
      JOURNEY_DATABASE_PASSWORD: ${JOURNEY_DATABASE_PASSWORD}
      JOURNEY_DATABASE_PORT: 5432
      JOURNEY_DATABASE_HOST: ${JOURNEY_DATABASE_HOST:-postgres}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - journey

  postgres:
    image: "postgres:16.2-alpine3.19"
    container_name: api-db
    ports:
      - ${JOURNEY_DATABASE_PORT}:5432
    environment:
      POSTGRES_USER: ${JOURNEY_DATABASE_USER}
      POSTGRES_DB: ${JOURNEY_DATABASE_NAME}
      POSTGRES_PASSWORD: ${JOURNEY_DATABASE_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${JOURNEY_DATABASE_USER} -d ${JOURNEY_DATABASE_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - journey

networks:
  journey:
    driver: bridge