name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: 'Build and Push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Generate SHA
        id: generate_sha
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Login into the container registry
        uses: docker/login-action@v3
        with:
          username: diogenesoliver
          password: dckr_pat_GycOjLDfgoyG3oG6j3O2CSI7VuA

      - name: Build docker image
        run: docker build -t diogenesoliver/nlw-journey-go:${{ steps.generate_sha.outputs.sha }} .\